spring:
  config:
    import: classpath:/env.yml
  application:
    name: jangan-backend


  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    database: mysql
#    hibernate:
#      ddl-auto: update  # ??? ?? create, update, validate, none ?? ??
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true  # ??? SQL ?? ??
#    open-in-view: false  # ?? ???? ?? ???? ??

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket:
    name: jangan